/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chatbox.gui;

import com.chatbox.dao.UserService;
import com.chatbox.dto.User;
import com.chatbox.exception.AppException;
import java.awt.Panel;
import javax.swing.JPanel;

/**
 *
 * @author vigneshwaran
 */
public class ChatAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChatAppFrame
     */
    public ChatAppFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel header = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        bodyTabbedPanel = new javax.swing.JTabbedPane();
        chatPanel = new javax.swing.JPanel();
        registerForm = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        registerNameInput = new javax.swing.JTextField();
        regispasswordLabel = new javax.swing.JLabel();
        registerPasswordInput = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        registerPopupMessage = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        popupMessage = new javax.swing.JLabel();
        loginMessagePanel = new javax.swing.JPanel();
        loginMessage = new javax.swing.JLabel();
        goToRegisterButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        hiLabel = new javax.swing.JLabel();
        welcomeUserNameLabel = new javax.swing.JLabel();
        goToJoinAGroup = new javax.swing.JButton();
        goToGroupCreation = new javax.swing.JButton();
        joinCreateFormLayeredPane = new javax.swing.JLayeredPane();
        createGroupForm = new javax.swing.JPanel();
        createGroupPort = new javax.swing.JLabel();
        createGroupPortInput = new javax.swing.JTextField();
        createGroupName = new javax.swing.JLabel();
        createGroupNameInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        joinGroupForm = new javax.swing.JPanel();
        joinGroupHost = new javax.swing.JLabel();
        joinGroupHostInput = new javax.swing.JTextField();
        joinGroupPort = new javax.swing.JLabel();
        joinGroupPortInput = new javax.swing.JTextField();
        joinGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 900, 600));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));

        headerLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("ChatBox");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(485, 485, 485))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1081, -1));

        bodyTabbedPanel.setBackground(new java.awt.Color(0, 255, 255));
        bodyTabbedPanel.setMaximumSize(new java.awt.Dimension(900, 581));

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1081, Short.MAX_VALUE)
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );

        bodyTabbedPanel.addTab("tab2", chatPanel);

        nameLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nameLabel1.setText("Name");

        registerNameInput.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        registerNameInput.setToolTipText("Name");

        regispasswordLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        regispasswordLabel.setText("Password");

        registerPasswordInput.setToolTipText("Passowrd");

        registerButton.setBackground(new java.awt.Color(0, 0, 0));
        registerButton.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRegister(evt);
            }
        });

        registerPopupMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout registerFormLayout = new javax.swing.GroupLayout(registerForm);
        registerForm.setLayout(registerFormLayout);
        registerFormLayout.setHorizontalGroup(
            registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerFormLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPopupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(registerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addComponent(regispasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(registerPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registerButton))
                .addContainerGap(701, Short.MAX_VALUE))
        );
        registerFormLayout.setVerticalGroup(
            registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerFormLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(registerPopupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regispasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(registerButton)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        bodyTabbedPanel.addTab("tab3", registerForm);

        loginPanel.setBackground(new java.awt.Color(0, 255, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(900, 550));
        loginPanel.setMinimumSize(new java.awt.Dimension(900, 550));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nameLabel.setText("Name");
        loginPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 90, 30));

        nameInput.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nameInput.setToolTipText("Name");
        loginPanel.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, 30));

        passwordLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 30));

        passwordInput.setToolTipText("Passowrd");
        loginPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 30));

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLogin(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        popupMessage.setForeground(new java.awt.Color(255, 0, 0));
        loginPanel.add(popupMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 140, 20));

        loginMessagePanel.setBackground(new java.awt.Color(0, 0, 0));
        loginMessagePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        loginMessage.setBackground(new java.awt.Color(0, 0, 0));
        loginMessage.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        loginMessage.setForeground(new java.awt.Color(255, 255, 255));
        loginMessage.setText("Everyone is waiting for you ...");

        javax.swing.GroupLayout loginMessagePanelLayout = new javax.swing.GroupLayout(loginMessagePanel);
        loginMessagePanel.setLayout(loginMessagePanelLayout);
        loginMessagePanelLayout.setHorizontalGroup(
            loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMessagePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(loginMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        loginMessagePanelLayout.setVerticalGroup(
            loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMessagePanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(loginMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        loginPanel.add(loginMessagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 570, 500));

        goToRegisterButton.setBackground(new java.awt.Color(0, 0, 0));
        goToRegisterButton.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        goToRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        goToRegisterButton.setText("Register");
        goToRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRegisterPanel(evt);
            }
        });
        loginPanel.add(goToRegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        bodyTabbedPanel.addTab("tab1", loginPanel);

        hiLabel.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        hiLabel.setText("Hi");

        welcomeUserNameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N

        goToJoinAGroup.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        goToJoinAGroup.setText("Join a Group");
        goToJoinAGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onJoinButtonPressed(evt);
            }
        });

        goToGroupCreation.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        goToGroupCreation.setText("Create a Group");
        goToGroupCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateGroupPressed(evt);
            }
        });

        joinCreateFormLayeredPane.setLayout(new java.awt.CardLayout());

        createGroupPort.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        createGroupPort.setText("Port");

        createGroupPortInput.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        createGroupPortInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupPortInputActionPerformed(evt);
            }
        });

        createGroupName.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        createGroupName.setText("Group Name");

        createGroupNameInput.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateGroupButtonPressed(evt);
            }
        });

        javax.swing.GroupLayout createGroupFormLayout = new javax.swing.GroupLayout(createGroupForm);
        createGroupForm.setLayout(createGroupFormLayout);
        createGroupFormLayout.setHorizontalGroup(
            createGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createGroupFormLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(createGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(createGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(createGroupFormLayout.createSequentialGroup()
                            .addComponent(createGroupName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(createGroupNameInput))
                        .addGroup(createGroupFormLayout.createSequentialGroup()
                            .addComponent(createGroupPort, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(createGroupPortInput, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        createGroupFormLayout.setVerticalGroup(
            createGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createGroupFormLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(createGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGroupPort)
                    .addComponent(createGroupPortInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGroupName)
                    .addComponent(createGroupNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        joinCreateFormLayeredPane.add(createGroupForm, "card3");

        joinGroupHost.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        joinGroupHost.setText("Host Address");

        joinGroupHostInput.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        joinGroupPort.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        joinGroupPort.setText("Port");

        joinGroupPortInput.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        joinGroupButton.setText("Join");
        joinGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onJoinGroupPressed(evt);
            }
        });

        javax.swing.GroupLayout joinGroupFormLayout = new javax.swing.GroupLayout(joinGroupForm);
        joinGroupForm.setLayout(joinGroupFormLayout);
        joinGroupFormLayout.setHorizontalGroup(
            joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinGroupFormLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joinGroupButton)
                    .addGroup(joinGroupFormLayout.createSequentialGroup()
                        .addGroup(joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(joinGroupHost)
                            .addComponent(joinGroupPort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(joinGroupHostInput)
                            .addComponent(joinGroupPortInput, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        joinGroupFormLayout.setVerticalGroup(
            joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinGroupFormLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinGroupHost)
                    .addComponent(joinGroupHostInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(joinGroupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinGroupPort)
                    .addComponent(joinGroupPortInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(joinGroupButton)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        joinCreateFormLayeredPane.add(joinGroupForm, "card2");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(hiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcomeUserNameLabel))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(goToJoinAGroup)
                        .addGap(49, 49, 49)
                        .addComponent(goToGroupCreation)))
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(joinCreateFormLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiLabel)
                    .addComponent(welcomeUserNameLabel))
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(goToGroupCreation))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goToJoinAGroup)))
                .addGap(18, 18, 18)
                .addComponent(joinCreateFormLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        bodyTabbedPanel.addTab("tab4", homePanel);

        getContentPane().add(bodyTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1081, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLogin
        String userName = nameInput.getText();
        String userPassword = new String(passwordInput.getPassword());
        
        try {
            if(!UserService.getInstance().isValidUser(userName, userPassword)) {
                popupMessage.setText("Invalid credintials");
                return;
            }
            showHomePage(UserService.getInstance().findByUserName(userName).get());
        }
        catch(AppException e) {
            popupMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_onLogin

    private void onRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRegister
        String userName = registerNameInput.getText();
        String userPassword = new String(registerPasswordInput.getPassword());
        
        try {
            Long userId = UserService.getInstance().addUser(userName, userPassword);
            if(userId == -1) {
                registerPopupMessage.setText("Error while creating user");
                return;
            }    
            showHomePage(new User(userId, userName));
        }
        catch(AppException e) {
            registerPopupMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_onRegister

    private void goToRegisterPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRegisterPanel
        showReigsterPanel();
    }//GEN-LAST:event_goToRegisterPanel

    private void onJoinButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onJoinButtonPressed
        switchJoinCreateForm(joinGroupForm);
    }//GEN-LAST:event_onJoinButtonPressed

    private void onCreateGroupPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateGroupPressed
        switchJoinCreateForm(createGroupForm);
    }//GEN-LAST:event_onCreateGroupPressed

    private void createGroupPortInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupPortInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createGroupPortInputActionPerformed

    private void onJoinGroupPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onJoinGroupPressed
        String host = joinGroupHost.getText();
        int port = Integer.parseInt(joinGroupPort.getText());
        
    }//GEN-LAST:event_onJoinGroupPressed

    private void onCreateGroupButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateGroupButtonPressed
        int port = Integer.parseInt(createGroupPort.getText());
        String groupName = createGroupName.getText();
        
        
    }//GEN-LAST:event_onCreateGroupButtonPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatAppFrame().setVisible(true);
            }
        });
    }
    
    private void switchJoinCreateForm(JPanel panel) {
        joinCreateFormLayeredPane.removeAll();
        joinCreateFormLayeredPane.add(panel);
        joinCreateFormLayeredPane.repaint();
        joinCreateFormLayeredPane.revalidate();
    }
    
    public void showLoginPage() {
        bodyTabbedPanel.setSelectedIndex(2);
    }
    
    public void showHomePage(User user) {
        bodyTabbedPanel.setSelectedIndex(3);
        welcomeUserNameLabel.setText(user.getName());
    }
    
    public void showReigsterPanel() {
        bodyTabbedPanel.setSelectedIndex(1);
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane bodyTabbedPanel;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JPanel createGroupForm;
    private javax.swing.JLabel createGroupName;
    private javax.swing.JTextField createGroupNameInput;
    private javax.swing.JLabel createGroupPort;
    private javax.swing.JTextField createGroupPortInput;
    private javax.swing.JButton goToGroupCreation;
    private javax.swing.JButton goToJoinAGroup;
    private javax.swing.JButton goToRegisterButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel hiLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane joinCreateFormLayeredPane;
    private javax.swing.JButton joinGroupButton;
    private javax.swing.JPanel joinGroupForm;
    private javax.swing.JLabel joinGroupHost;
    private javax.swing.JTextField joinGroupHostInput;
    private javax.swing.JLabel joinGroupPort;
    private javax.swing.JTextField joinGroupPortInput;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginMessage;
    private javax.swing.JPanel loginMessagePanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel popupMessage;
    private javax.swing.JLabel regispasswordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerForm;
    private javax.swing.JTextField registerNameInput;
    private javax.swing.JPasswordField registerPasswordInput;
    private javax.swing.JLabel registerPopupMessage;
    private javax.swing.JLabel welcomeUserNameLabel;
    // End of variables declaration//GEN-END:variables
}
